#!/bin/bash

_find_unscoped_vars() {
   local file
   local unscoped_vars

   for file in $HOME/.bashrc.d/functions/*; do
      for var in $(grep -hoP '^ *\K[^][ ]+=' "$file" | cut -d= -f1); do
         grep -q "local $var" "$file" || unscoped_vars+=("$(cat -n "$file" | sed -rne "s;^\s+([0-9]+)\s+("$var")=.*;\1:\2;p" | head -n1)")
      done

      if [[ ${#unscoped_vars[*]} -gt 0 ]]; then
         echo -e "$file\nthese vars need to be scoped to 'local':"

         for i in ${unscoped_vars[*]}; do
            echo "$i"
         done

         echo

         unset unscoped_vars
      fi
   done
}
