#!/bin/bash

_print_var_vals() {

   # takes all arguments and prints out their values (for debugging)
   # this assumes all arguments are indeed variables
   # any argumentsthat aren't variables, are unset, or have no assigned
   # value are still accepted and simply printed to indicate no value

   # input: a list of variable names
   # output: the list of variable names, along with their values, if any

   _verify_reqs <<-EOF || return 1
	verbose
	EOF

   local i
   for i in $@; do
      # ensure the given arg is actually a variable and has been set
      [[ -v $i ]] || continue
      declare -n _variable="$i"
      verbose 8 "${FUNCNAME[$((funcname_lineno_index + 1))]} (line ${BASH_LINENO[$funcname_lineno_index]}): $i = $_variable"
   done
}
