#!/bin/bash

#bar_graph() {
#   graphChar=".";
#   scale=1;
#   for date in 03; do
#      for hour in {01..23}; do
#         echo -n "2013-01-$date $hour: ";
#         emails=$(shuf -i10-200 -n1);
#			printf "$graphChar%.0s" $(seq 1 $emails)
#         echo;
#      done;
#      echo;
#   done
#}
#sudo journalctl --quiet --grep=': CTRL-EVENT-SIGNAL-CHANGE' -u wpa_supplicant | cut -d: -f1-2 | sort | sed -e 's;.$;0;' | uniq -c | sort -k3 -k4d -h | awk '{ printf("%s %s %s ",$2,$3,$4); for(i = 1; i <= $1; i++) printf("%s","="); printf(" (%s)\n",$1)}'; date
