#!/bin/bash

diff-home-files() {
   local i
   local HOME_DIR="$HOME/home"
   local ACTION="${1:-diff}"

   _help() {
      # bash 5 doesn't like <<- heredocs with leading tabs within nested functions
      echo "
		Commands:

		[cp|copy|-a]      copy files from ~/ to $HOME_DIR non-interactively

		[diff|vimdiff]    use vimdiff to compare each file that differs between ~/ and $HOME_DIR
		" | tr -d '\t'
   }

   case "$ACTION" in
      diff|vimdiff)
         ACTION="vimdiff"
         ;;
      copy|cp|-a)
         ACTION="cp -aiv"
         ;;
      *)
         _help
         return
         ;;
   esac

   # list files that should be ignored
   # filenames relative to $HOME_DIR
   declare -a skip_files=(
   ".bashrc"
   ".bashrc.d/functions/_verify_reqs"
   ".bashrc.d/functions/yessh"
   ".htoprc"
   ".zshrc"
   "etc/hosts"
   "etc/logrotate.d/chrome-history"
   "etc/sudoers"
   "etc/sudoers.d/laptop-sleep"
   "var/spool/cron/crontabs/username"
   )
   for i in $(find $HOME_DIR -type f ! -iregex '.*\/\.git\/.*'); do
      # check if the file should be skipped
      echo "$i" | grep -qxf <(for i in  ${skip_files[*]}; do echo "$HOME_DIR/$i"; done) && {
         echo "skipping ignored file '$i'..."
         continue
      }

      # the item is within the .bashrc.d directory
      [[ -f "$i" ]] || continue

      # and it isn't .toprc, and it's not a vim swap file
      [[ ! "$i" =~ \.toprc &&
      ! $(file $i) =~ "Vim swap file" &&
      ! "$i" =~ \.md &&
      ! "$i" =~ \.vim\/ ]] || continue
#      echo "i = $i"

      local file1="$(echo "$i" | sed -re "s;$HOME_DIR/(.*);$HOME/\1;")"
#      echo file1="$file1"

      local file2=$i
#      echo file2="$file2"
      [[ $(md5sum $file1 2>/dev/null | cut -d" " -f1) != $(md5sum $file2 2>/dev/null | cut -d" " -f1) ]] && $ACTION $file1 $file2
   done

   local missed_files
   for i in $HOME/.bashrc.d/*/*; do
      [[ -h "$i" ]] && continue
      [[ -f ${i/$HOME\//$HOME_DIR/} ]] || missed_files+=$'\1'"$i"
   done

   if [[ "$missed_files" ]]; then
      echo
      echo "you may want to copy these to $HOME_DIR:"
      echo "$missed_files" | tr '\1' '\n'
   fi
}
