#!/bin/bash

diff-home-files() {
   local i
   for i in $(find $HOME/home/ -type f ! -iregex '.*\/\.git\/.*'); do
      # the item is within the .bashrc.d directory
      [[ -f "$i" ]] || continue

      # and it isn't .toprc, and it's not a vim swap file
      [[ ! "$i" =~ \.toprc &&
      ! $(file $i) =~ "Vim swap file" &&
      ! "$i" =~ \.md &&
      ! "$i" =~ \.vim\/ ]] || continue
#      echo "i = $i"

      file1="$(echo "$i" | sed -re "s;$HOME/home/(.*);$HOME/\1;")"
#      echo file1="$file1"

      file2=$i
#      echo file2="$file2"
      [[ $(md5sum $file1 2>/dev/null | cut -d" " -f1) != $(md5sum $file2 2>/dev/null | cut -d" " -f1) ]] && vimdiff $file1 $file2
   done
}
