#!/bin/bash

fix-session-manager() {
   echo "SESSION_MANAGER = '$SESSION_MANAGER'"
   [[ "${TERM_PROGRAM}" =~ ^tmux ]] && {
      # FIXME: fix for slow vim startup in tmux
      SESSION_PID=$(ls -1tr /tmp/.ICE-unix/ | tail -n1)
      echo "SESSION_MANAGER = '$SESSION_MANAGER'"
      export SESSION_MANAGER="local/${HOSTNAME}:@/tmp/.ICE-unix/${SESSION_PID},unix/${HOSTNAME}:/tmp/.ICE-unix/${SESSION_PID}"
      echo "SESSION_MANAGER = '$SESSION_MANAGER'"
   }
}
