#!/bin/bash

list-to-quoted-csv() {
   # takes a file of newline-separated output and converts it to quoted CSV

   _verify_reqs <<-EOF || return 1
      _get_stdin
	EOF

   local input="$(_get_stdin "$1")"
   local no_quotes="$2"
   local quotes='"'

   [[ "$no_quotes" =~ nq ]] && quotes=""
   echo "$input" | sed -rne "s;^.*$;${quotes}&${quotes}\,;gp" | tr -d '\n' | sed -re 's;(^,|,$);;g' -e 's;$;\n;'
}
