#!/bin/bash

list-to-quoted-csv() {
   # takes a file of newline-separated output and converts it to quoted CSV

   _verify_reqs <<-EOF || return 1
      _get_stdin
	EOF

   local input="$(_get_stdin "$1")"
   local start_quote="${2:-}"
   [[ "${#start_quote}" -ne 1 ]] || {
      echo "error: must be a single character (excluding an escape)"
      return 1
   }
   [[ "${start_quote}" =~ []}\)] ]] && start_quote="$(echo "${start_quote}" | tr '}])' '{[(')"
   local end_quote="${start_quote}"
#   echo "input = '${input}'"
#   echo "start_quote = '${start_quote}'"
#   echo "end_quote = '${end_quote}'"
   [[ "${start_quote}" =~ [[{\(] ]] && end_quote="$(echo "${start_quote}" | tr '{[(' '}])')"


#   echo "$input" | sed -rne "s;^.*$;${quotes}&${quotes}\,;gp" | tr -d '\n' | sed -re 's;(^,|,$);;g' -e 's;$;\n;'
   echo "$input" | sed -rne "s;^.*$;${start_quote}&${end_quote};gp" | paste -sd,
}
