#!/bin/bash

tabular-to-csv() {
   #takes a file of standard MySQL tabular output and converts it to CSV

   _verify_reqs <<-EOF || return 1
      _get_stdin
	EOF

   local tabular_contents="$(_get_stdin "$1")"

   echo "$tabular_contents" | sed -rne 's; *\| *;,;gp' | sed -re 's;(^,|,$);;g'
}
