#!/bin/bash

aptupchange() {
   # view the changelogs of all packages to be upgraded

   local packages_temp="$(sudo apt-get -us upgrade | sed -ne "s;^Inst \([^[]\+\) \([[(]\).*;\1;"p)"
   [[ -n "${packages_temp}" ]] || {
      echo "no packages to be upgraded"
      return 1
   }
   declare -a packages=($(echo "${packages_temp}" | sort))

   echo "packages to be upgraded:"
   local package
   for package in "${packages[@]}"; do
      echo "${package}"
   done
   echo

   for package in "${packages[@]}"; do
      echo -n "view changelog for '${package}'? [y/N]: "

      read

      [[ "${REPLY}" = "y" ]] &&
       aptchangelog "${package}" &&
       echo
   done
}
