#!/bin/bash

# gets battery power percentage
# this can add a second to execute the subshell each time it's sourced
alias get-bat-level="upower -i $(upower --enumerate | grep BAT | head -n1) | awk '/percentage/ {print $2}' | tr -s ' '"

if [[ "${SHELL}" =~ zsh$ || "${SHELL_TYPE}" =~ ^zsh$ ]]; then
   alias cb="bash -ic 'blueconnect buds'"
   alias cn="bash -ic 'blueconnect speaker'"
else
   alias cb='blueconnect buds'
   alias cn='blueconnect speaker'
fi
