#!/usr/bin/env bash

# 1password
has op && . <(op completion "${SHELL_TYPE}")
is_zsh && compdef _op op

# docker
if has docker; then
   COMPLETION_DIR="${HOME}/.local/completions"
   [[ -d "${COMPLETION_DIR}" ]] || mkdir -p "${COMPLETION_DIR}"

   # default to Bash completion
   DOCKER_COMPLETION_FILE="${COMPLETION_DIR}/_docker.sh"
   DOCKER_COMPLETION_FILE_URL="https://raw.githubusercontent.com/docker/cli/master/contrib/completion/bash/docker"

   if is_zsh; then
      DOCKER_COMPLETION_FILE="${COMPLETION_DIR}/_docker.zsh"
      DOCKER_COMPLETION_FILE_URL="https://raw.githubusercontent.com/docker/cli/master/contrib/completion/zsh/_docker"

      zstyle ':completion:*:*:docker:*' option-stacking yes
      zstyle ':completion:*:*:docker-*:*' option-stacking yes
   fi

   [[ -s "${DOCKER_COMPLETION_FILE}" ]] || {
      curl -sLo "${DOCKER_COMPLETION_FILE}" "${DOCKER_COMPLETION_FILE_URL}"
   }

   . "${DOCKER_COMPLETION_FILE}"
   unset DOCKER_COMPLETION_FILE
   unset DOCKER_COMPLETION_FILE_URL
   unset COMPLETION_DIR
fi

# dotfile manager
has chezmoi && . <(chezmoi completion "${SHELL_TYPE}")
is_zsh && compdef _chezmoi chezmoi

# github-cli
has gh && . <(gh completion -s "${SHELL_TYPE}")
is_zsh && compdef _gh gh

# gitlab-cli
has glab && . <(glab completion -s "${SHELL_TYPE}")
is_zsh && compdef _glab glab

# helm
has helm && . <(helm completion "${SHELL_TYPE}")

# k8s
has kubectl && {
   if has kubecolor; then
      alias k='kubecolor'
   else
      alias k='kubectl'
   fi

   . <(kubectl completion "${SHELL_TYPE}")

   if is_zsh; then
      # k alias hack TODO: remember compdef load order
      compdef k=kubectl
   else
      complete -o default -F __start_kubectl k
   fi
}

# minikube
has minikube && {
   . <(minikube completion "${SHELL_TYPE}")
   alias mk='minikube kubectl --'
}

# starship
has starship && . <(starship completions "${SHELL_TYPE}")

# glow
# https://github.com/charmbracelet/glow
has glow && . <(glow completion "${SHELL_TYPE}")
