#!/bin/bash

archive-emails() {
   # input: optional time specification to indicate the week you'd like to review (defaults to last week)
   # output: a GMail URL that searches for emails received during the specified (or default) week

   # example:
   # google-chrome $(archive-last-week-emails '3 weeks ago')

   local dateFormat="%m-%d-%Y"
   local beginning_of_week="1" # numeric version of day
   declare -A beginning_of_week_designation=(
   [0]="w"
   [1]="u"
   )
   local given_date="${@:-1 week ago}" # default to last week
   given_date="$(date -d "$given_date")"
   _print_var_vals given_date
#   local weekOf="$(date -d "now - $(($(date +%w) + 6)) days" +%F)" #calculate the beginning of last week

   [[ $(date -d "$given_date" +%j | sed -re 's;^0*([0-9]+)$;\1;') -gt $(date -d "now" +%j | sed -re 's;^0*([0-9]+)$;\1;') ]] && {
      echo "date must be in the past or present!"
      return 1
   }

   # calculate the beginning of the week of the given day
   weekOf="$(date -d "$given_date - $(($(date -d "$given_date" +%${beginning_of_week_designation[$beginning_of_week]}) - $beginning_of_week)) days" +%F)" # editorconfig-checker-disable-line
   _print_var_vals given_date weekOf beginning_of_week

   date -d "$weekOf" +%w &>/dev/null || return 1

   local weekStart="$(date -d "$weekOf - 1 day")"
   local weekEnd="$(date -d "$weekStart + 8 days")"
   _print_var_vals weekOf weekStart weekEnd

   echo "https://mail.google.com/mail/u/0/#search/after%3A$(date -d "$weekStart" "+$dateFormat")+before%3A$(date -d "$weekEnd" "+$dateFormat")+in%3Ainbox" # editorconfig-checker-disable-line
}
