#!/bin/bash

# check into bash completion with functions:
# <https://ubuntuforums.org/showthread.php?t=733397>
# <https://unix.stackexchange.com/questions/4219/how-do-i-get-bash-completion-for-command-aliases/4220#4220>
# <https://www.tldp.org/LDP/abs/html/tabexpansion.html>

for funcfile in $(realpath $(dirname "$BASH_SOURCE"))/functions/*; do
   [[ -d "$funcfile" ]] && continue
   funcname="$(sed -rne '3 s;^(function\s+)?([^#( ]+)\(\) \{$;\2;p' "$funcfile")"

   # export all the functions here so subshells can utilize them, if needed
   # for some reason, exported pushd() causes issues in direnv-allowed directories
   # though simply sourced (and not exported) pushd() is fine
   # also, we don't want to source and export files with functions that don't match their filenames
   {
      # test conditions
      [[ "$funcname" =~ ^${funcfile//*\/}$ ]] &&
      [[ -r "$funcfile" ]] &&
      file -L --mime-type "$funcfile" | grep -q 'text/x-shellscript' &&
      bash -n "$funcfile" 2>/dev/null
   } && {
      # unset the function if it already exists so we start fresh
      # then export the function
      [[ $(type -t $funcname) =~ ^function$ ]] && unset -f funcname
      . "$funcfile" &&
      [[ ! "$funcfile" =~ pushd ]] &&
      export -f "$funcname"
   }
done
unset funcfile funcname
