#!/bin/bash

# check into bash completion with functions:
# <https://ubuntuforums.org/showthread.php?t=733397>
# <https://unix.stackexchange.com/questions/4219/how-do-i-get-bash-completion-for-command-aliases/4220#4220>
# <https://www.tldp.org/LDP/abs/html/tabexpansion.html>

# export all the functions here so subshells can utilize them, if needed
for func in $(sed -rne 's;^(function\s+)?([^#( ]+)\(\) \{$;\2;p' "$BASH_SOURCE"); do
   # for some reason, exported pushd() causes issues in direnv allowed directories
   [[ "$func" =~ pushd ]] || export -f "$func"
done

for func in $(realpath $(dirname "$BASH_SOURCE"))/functions/*; do
   # for some reason, exported pushd() causes issues in direnv allowed directories
   if egrep -q '^(function\s+)?([^#( ]+)\(\) \{$' "$func"; then
      . "$func"
      [[ "$func" =~ pushd ]] || export -f "${func//*\/}"
   fi
done
unset func
