#!/usr/bin/env bash

# this must be copied to /lib/systemd/system-sleep/change_theme
#
# ensure it also has 755 perms and is owned by root

# REPLACE "\$(id -u)" WITH YOUR USER ID
# REPLACE "\$(id -un)" WITH YOUR USERNAME

PM_ACTION="${1}"
DARK_THEME='Yaru-viridian-dark'
LIGHT_THEME='Yaru-viridian'
DARK_START=18
DARK_STOP=7
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/\$(id -u)/bus" # may be needed for cron to run when logged out

log() {
   echo "$(date '+%F %T %Z') ${*}"
}

set_theme() {
   theme_type="${1:-dark}"
   color_scheme="prefer-${theme_type}"

   if [[ "${theme_type}" =~ ^dark$ ]]; then
      theme="${DARK_THEME}"
   elif [[ "${theme_type}" =~ ^light$ ]]; then
      theme="${LIGHT_THEME}"
   else
      echo "error: theme-type must be 'light' or 'dark'"
      return 1
   fi

   {
      log "gsettings set org.gnome.desktop.interface color-scheme '${color_scheme}'"
      log "gsettings set org.gnome.desktop.interface gtk-theme ${theme}"
   } >>/tmp/theme.log
   /bin/su "\$(id -un)" -c "gsettings set org.gnome.desktop.interface color-scheme '${color_scheme}'"
   /bin/su "\$(id -un)" -c "gsettings set org.gnome.desktop.interface gtk-theme '${theme}'"
}

{
   echo
   log "running $0"
} >>/tmp/theme.log

# set the dark theme if run during the dark theme hours

# normally, cron should run this file
# if this file is in /lib/systemd/system-sleep/ (/etc/pm/sleep.d/ doesn't work), this will also trigger when waking from sleep/hibernation in Ubuntu
if [[
      "${PM_ACTION}" =~ ^post$ ||
      -z "${PM_ACTION}"
   ]]; then
   if [[
         "$(date +%H)" -ge "${DARK_START}" ||
         "$(date +%H)" -lt "${DARK_STOP}"
      ]]; then
      # the full command paths may not be necessary
      set_theme dark
   else
      set_theme light
   fi
fi
