---
# ENABLE_LINTERS:
#   - SHELLCHECK
#   - SHFMT
DISABLE_LINTERS:
  - SPELL_CSPELL
REPOSITORY_CHECKOV_ARGUMENTS: "--skip-check CKV_GHA_7"
REPOSITORY_CHECKOV_CONFIG_FILE: ci/.checkov.yaml
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: ci/.markdownlint.yaml
