---
ENABLE_LINTERS:
  - ACTION_ACTIONLINT
  - BASH_SHELLCHECK
  # - BASH_SHFMT
  - EDITORCONFIG_EDITORCONFIG_CHECKER
  - MAKEFILE_CHECKMAKE
  # - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - MARKDOWN_REMARK_LINT
  - SPELL_MISSPELL
  - SPELL_LYCHEE
  - YAML_V8R
DISABLE_LINTERS:
  - SPELL_CSPELL
  - SPELL_PROSELINT

PRINT_ALL_FILES: true

ACTION_ACTIONLINT_ARGUMENTS: -shellcheck= -ignore 'property "get-changed-files" is not defined in object type {}'

BASH_SHELLCHECK_ARGUMENTS: -W 50 --color=always --severity=error
BASH_SHELLCHECK_FILE_NAMES_REGEX:
  - '[-a-z_.0-9]+'
BASH_SHELLCHECK_FILTER_REGEX_INCLUDE: (scripts|\.(shellrc\.d/|gitconfig\.d/git-sync.sh|githooks|(bash|mac|apple_keyboard_mod\.)rc))
BASH_SHELLCHECK_PRE_COMMANDS:
  - command: ln -s ci/.shellcheckrc . # necessary since shellcheck doesn't let you speconfig the config file
    cwd: 'workspace'

EDITORCONFIG_EDITORCONFIG_CHECKER_CONFIG_FILE: ci/.ecrc.json

MAKEFILE_CHECKMAKE_CONFIG_FILE: ci/.checkmake.ini
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: ci/.markdownlint.yaml

REPOSITORY_CHECKOV_ARGUMENTS: '--skip-check CKV_GHA_7'
REPOSITORY_CHECKOV_CONFIG_FILE: ci/.checkov.yaml

SPELL_LYCHEE_CONFIG_FILE: ci/lychee.toml

YAML_V8R_FILTER_REGEX_EXCLUDE: pre-commit.ya?ml
