name: pre-commit

# Controls when the workflow will run
on:
  push:
    paths:
       - '.github/workflows/pre-commit.yml'
       - '.pre-commit-config.yaml'
  pull_request:
    paths:
       - '.github/workflows/pre-commit.yml'
       - '.pre-commit-config.yaml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install go
        # required due to this issue:
        # package mvdan.cc/sh/v3/cmd/shfmt@v3.7.0: can only use path@version syntax with 'go get'
        # https://www.reddit.com/r/golang/comments/n628db/go_install_fails_with_can_only_use_pathversion/
        if: ${{ env.ACT }}
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.21'
          check-latest: true
      - name: Lint the repository with pre-commit
        run: |
          python3 -V
          pip3 install --upgrade pip
          pip3 install pre-commit==2.20.0
          pre-commit run --verbose


  # this only checks if the README had been generated; it can't itself commit
  # the generated file
  check-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install envsubst
        # this is required when using nektos/act due to this sort of issue with
        # act's ubuntu:latest image (it's still on 20.04):
        if: ${{ env.ACT }}
        run: apt-get install gettext-base

      - name: Ensure Documentation Was Generated
        run: |
          README_FILENAME="README.md"
          if [[ -s "${README_FILENAME}" ]]; then
            ORIG_CHECKSUM="$(md5sum "${README_FILENAME}")"
            mv -v "${README_FILENAME}" "${README_FILENAME}.orig"
            make readme
            NEW_CHECKSUM="$(md5sum "${README_FILENAME}")"
            [[ "${ORIG_CHECKSUM}" == "${NEW_CHECKSUM}" ]] || {
              echo "error: ${README_FILENAME} was not generated"
              echo
              echo "Generate the documentation using this command, then commit and push:"
              echo
              echo "    make readme
              echo
              exit 1
            }
          else
            echo "error: ${README_FILENAME} doesn't exist or is empty"
            exit 1
          fi
